services:
    twomartens.core.twig_extension:
        class: TwoMartens\Bundle\CoreBundle\Twig\TwoMartensCoreBundleExtension
        public: false
        tags:
            - { name: twig.extension }
    twomartens.core.block_systemstats.listener:
        class: TwoMartens\Bundle\CoreBundle\EventListener\SystemStatsDashboardListener
        arguments: [@templating, @translator]
        tags:
            - { name: kernel.event_listener, event: 'sonata.block.event.acp.dashboard', method: onBlock }
